### Local Successful Login
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "Password123!"
}

### Local Failed Login
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "wrong"
}

### Home page
GET cst8919-lab2-webapp-d4d3fqfveghdfjgr.westus3-01.azurewebsites.net

### Successful login
POST cst8919-lab2-webapp-d4d3fqfveghdfjgr.westus3-01.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password123!"
}

### Failed login 1
POST cst8919-lab2-webapp-d4d3fqfveghdfjgr.westus3-01.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrongpassword"
}

### Failed login 2
POST cst8919-lab2-webapp-d4d3fqfveghdfjgr.westus3-01.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrongpassword"
}